config/routes.rb
Earth2::Application.routes.draw do
  
  resources :users
  resources :welcome
  resources :sessions
  resources :countries, only: :index
  resources :capitals, only: :index

  resources :newsfeeds, only: :create

  root to: "welcome#index"
  

end

app/models/capital.rb
class Capital < ActiveRecord::Base
	geocoded_by :name
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :country
end

app/models/country.rb
class Country < ActiveRecord::Base
	geocoded_by :name
	has_many :cities
	has_and_belongs_to_many :newsfeeds
	has_many :users, through: :newsfeeds
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/newsfeed.rb
class Newsfeed < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :countries
end

app/models/region.rb
class Region < ActiveRecord::Base
end

app/models/ticker.rb
class Ticker < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password 

	validates_presence_of :email

	has_one :newsfeed
end

app/controllers/capitals_controller.rb
class CapitalsController < ApplicationController
	def index
		@capitals = Capital.all
		respond_to do |format|
			format.json {
				render json: @capitals.to_json(only: [:id, :name, :latitude, :longitude])
			}
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end 

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_path
		else 
			render :new 
		end 
	end 

private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end 
end

app/controllers/welcome_controller.rb
require 'open-uri'

class WelcomeController < ApplicationController
  def index
	@user = User.new
	gon.newsfeed_path = url_for(newsfeeds_path)
	
 	top_articles_data = open("http://content.guardianapis.com/search?api-key=" + ENV["GUARDIAN_KEY"] + "&section=-football,-sport,-tv-and-radio").read
 	top_articles_json = JSON.parse(top_articles_data)
 	gon.news = top_articles_json["response"]["results"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capitals_helper.rb
module CapitalsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/ticker_helper.rb
module TickerHelper
end

app/helpers/tickers_helper.rb
module TickersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <%= include_gon %>
        <title>Earth2</title>
        <%= stylesheet_link_tag    "application", media: "all" %>
        <script type="text/javascript" src="https://www.google.com/jsapi"> </script>
        <script type="text/javascript">
            google.load("earth", "1", {"other_params":"sensor=true_or_false"});
            google.load('search', '1');
            google.load("elements", "1", {packages : ["newsshow"]});
        </script>

        <%= javascript_include_tag "application" %>

        <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
        <%= csrf_meta_tags %>
	</head>
	<body>
        <div id="branding">earth2</div>
        <br/>
        <div id="sample-ui">
            <div id="navbar">
            </div>
        </div>
		<div id="content">
			<div id="map3d"></div>
				<div id="outer">
					<div id="nav_bar">
						<!-- making it so you can't see the login and sign up buttons if you are logged in -->

						<div id="toggleBtn" class="nav_buttons" title="Show Newsfeed">
							<i class="fa fa-bars fa-2x earth-actions"></i>
						</div>
						<% if current_user %>
							<%= link_to session_path("current"), method: :delete do %>
								<i class = "fa fa-sign-out fa-2x earth-actions" title="Log out"></i>
							<% end %>
						<% else %>
							<div id="login_btn" class="nav_buttons" title="Log in">
                                <i class="fa fa-sign-in fa-2x earth-actions"></i>
							</div>
							<div id="signup_btn" class="nav_buttons" title="Sign up">
                                <i class="fa fa-user fa-2x earth-actions"></i>
							</div>
						<% end %>
						<div id="button-show-sky" class="nav_buttons" title="Outer Space">
                            <i class="fa fa-rocket fa-2x earth-actions"></i>
						</div>
						<div id="button-show-earth" class="nav_buttons" title="Return to Earth">
                            <i class="fa fa-globe fa-2x earth-actions"></i>
						</div>
						<div id="button-center" class="nav_buttons" title="Re-Centre Earth">
                            <i class="fa fa-crosshairs fa-2x earth-actions"></i>
						</div>
					</div>
					<div id="newsfeed">
                        <div id = "inner_newsfeed">
                            <div class="article"></div>
                        </div>
					</div>
				</div>
			</div>
			<div id="lower">
                <marquee id="ticker" behavior="scroll" direction="left" onmouseover="this.stop();" onmouseout="this.start();"></marquee>
			</div>
		</div>
		<% if current_user %>
			<p>Logged in as <%= current_user.name %>.</p>
		<% else %>
			<div id="sign_up_form" >
				<%= form_for(@user) do |f| %>
					<div class="field">
						<%= f.label :name %>
						<%= f.text_field :name %>
					</div>
					<div class="field">
						<%= f.label :email %>
						<%= f.text_field :email %>
					</div>
					<div class="field">
						<%= f.label :password %>
						<%= f.password_field :password %>
					</div>
					<div class="field">
						<%= f.label :password_confirmation %>
						<%= f.password_field :password_confirmation %>
					</div>
					<div class="actions">
						<%= f.submit "Sign up!" %>
					</div>
				<% end %>
			</div>
			<div id="login_form" >
				<%= form_tag sessions_path do |f| %>
					<div class="field">
						<%= label_tag :email %>
						<%= text_field_tag :email %>
					</div>
					<div class="field">
						<%= label_tag :password %>
						<%= password_field_tag :password %>
					</div>
					<div class="actions">
						<%= submit_tag "Log in!" %>
					</div>
				<% end %>
			</div>
		<% end %>
        <%= yield %>
	</body>
</html>